// <auto-generated />
using LinkShortnerDotNET.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace LinkShortnerDotNET.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200203152904_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1");

            modelBuilder.Entity("LinkShortnerDotNET.Models.LinkSet", b =>
                {
                    b.Property<string>("LinkId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.HasKey("LinkId");

                    b.ToTable("Links");
                });
#pragma warning restore 612, 618
        }
    }
}
